cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    # url(r'^home1', views.home1, name='home1'),
    # url(r'^uploads/simple/', views.simple_upload, name='simple_upload'),
    # url(r'^uploads/form/', views.model_form_upload, name='model_form_upload'),
    url(r'^ocr/$', views.ocr, name='ocr'),
    url(r'^maps', views.maps, name='maps'),
    url(r'^home/', views.home, name='home'),
    url(r'^add_item/', views.add_item, name='add_item'),
    url(r'^itemlist/', views.itemlist, name='itemlist'),
    url(r'^shoppingcart/', views.shoppingcart, name='shoppingcart'),
    url(r'^search/', views.searchpage , name='searchpage'),
    url(r'^searchnearbyshops/', views.searchnearbyshops , name='searchnearbyshops'),
    url(r'^searchitem/', views.search , name='search'),
    url(r'^sort_alphabet/', views.sort_alphabet , name='sort_alphabet'),
    url(r'^sort_desc_alphabet/', views.sort_desc_alphabet , name='sort_desc_alphabet'),
    url(r'^sort_price/', views.sort_price , name='sort_price'),
    url(r'^sort_desc_price/', views.sort_desc_price , name='sort_desc_price'),
    # url(r'^ocr/', ocr_view, name='ocr_view'),
    # url(r'^ocrform/', ocr_form_view, name='ocr_form_view'),
    url(r'^checkout/', views.checkout , name='checkout'),
    url(r'^productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url(r'^add_to_cart/(?P<Item_id>[0-9]+)',views.add_to_cart, name='add_to_cart'),
    url(r'^remove_from_cart/(?P<Item_id>[0-9]+)',views.remove_from_cart, name='remove_from_cart'),
    url(r'^remove_single_item_from_cart/(?P<Item_id>[0-9]+)',views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url(r'^add_single_item_into_cart/(?P<Item_id>[0-9]+)',views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

home/urls.py
from django.urls import path, include 
from django.conf import settings 
from . import views
from user import views as user_view 
from django.contrib.auth import views as auth
from django.conf.urls.static import static 
from django.conf.urls import url
from django.contrib.auth import views as auth_views


app_name = 'home'

urlpatterns=[
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

payment/urls.py
from django.conf.urls import url
from . import views

app_name = 'payment'

urlpatterns=[
    url(r'^process/$',views.payment_process,name='process'),
    url(r'^done/$',views.payment_done,name='done'),
    url(r'^cancelled/$',views.payment_cancelled,name='cancelled'),



]

cart/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# from user.models import Shop

class Document(models.Model):
    # description = models.CharField(max_length=255, blank=True)
    docfile = models.FileField(upload_to='documents/')
    # uploaded_at = models.DateTimeField(auto_now_add=True)

class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(blank=True,null=True)
    description = models.CharField(max_length=300)
    in_cart = models.BooleanField(default=False)
    image = models.CharField(blank=True, null=True, max_length=400)
    shop_having = models.ManyToManyField("user.Shop")

    def __str__(self):
        return self.name

class Cart(models.Model):
    #current_user =  models.ForeignKey(User, on_delete=models.CASCADE)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    itemtotal=models.FloatField(blank=True,null=True)
    #
    # def __str__(self):
    #     return str(self.current_user.username)

    def get_total_item_price(self):
        return self.quantity*self.item.price

home/models.py
from django.db import models

# Create your models here.

payment/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

from .models import Document


class DocumentForm(forms.Form):
    docfile = forms.FileField(label='Select a file')
    # class Meta:
    #     model = Document
    #     fields = ('description', 'document', )

cart/views.py
from .models import Item, Cart
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib import messages
from googlevoice import Voice
import requests
from math import radians, sin, asin, sqrt, cos
import urllib.parse
from django.http.response import JsonResponse
from django.views.generic.base import View, TemplateView
from django.views.decorators.csrf import csrf_exempt
# from PIL import Image, ImageFilter
# from tesserocr import PyTessBaseAPI
from user.models import Shop
# from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
import geocoder
from .models import Document
from .forms import DocumentForm
import json

try:
        import Image
except ImportError:
        from PIL import Image
import pytesseract


# class OcrFormView(TemplateView):
#     template_name = 'cart/ocr_form.html'
# ocr_form_view = OcrFormView.as_view()


# class OcrView(View):
#     def post(self, request, *args, **kwargs):
#         with PyTessBaseAPI() as api:
#             with Image.open(request.FILES['image']) as image:
#                 sharpened_image = image.filter(ImageFilter.SHARPEN)
#                 api.SetImage(sharpened_image)
#                 utf8_text = api.GetUTF8Text()

#         return JsonResponse({'utf8_text': utf8_text})
# ocr_view = csrf_exempt(OcrView.as_view())

from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from .models import Document
from .forms import DocumentForm

# global i
# i=0
def home1(request):
    documents = Document.objects.all()
    return render(request, 'cart/home.html', { 'documents': documents })


def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'cart/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'cart/simple_upload.html')


def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cart:home1')
    else:
        form = DocumentForm()
    return render(request, 'cart/model_form_upload.html', {
        'form': form
    })


def ocr(request):
    global i
    if request.method=="POST":
        i=4
        docs = Document.objects.all()
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            i += 1 
            print(i)
            # import ipdb;ipdb.set_trace()
            d = Document.objects.get(id=i)
            
            #print d.docfile
            k=pytesseract.image_to_string(Image.open(d.docfile))
            print(k)
            listofwords=k.split(' ')
            total_list = []
            for item in Item.objects.all():
                total_list.append(item.name.lower())

            flag=0
            for word in listofwords:
                if word in total_list:
                    flag=1
                    print("Add item to cart")

            if flag==0:
                print("Oops!! No such item exists")

            handle = open('data.txt', 'a+')
            handle.write(k)
            handle.close()

            txt_file = r"data.txt"

            # Redirect to the document list after POST
            return redirect('cart:ocr')
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render(request, 'cart/list.html',{'documents': documents, 'form': form})


def home(request):
    all_items = Item.objects.all()
    if not request.user.is_authenticated:
        print('No one inside the app')
        num_items_in_cart = 0
        return render(request, 'cart/index.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})
    else:
        user = request.user
        num_items_in_cart = user.profile.cart_items.all().count()
        return render(request, 'cart/index.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})

def itemlist(request):
    all_items = Item.objects.all()
    user = request.user
    if not user.is_authenticated:
        num_items_in_cart=0
        return render(request, 'cart/itemlist.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})
    num_items_in_cart=user.profile.cart_items.all().count()
    return render(request, 'cart/itemlist.html', {'all_items': all_items , 'num_items_in_cart': num_items_in_cart})

def shoppingcart(request):
    user = request.user
    print("Hey Dude")
    if not user.is_authenticated:
        num_items_in_cart=0
        return render(request, 'cart/shopping-cart.html', {'num_items_in_cart': num_items_in_cart})
    all_user_items = user.profile.cart_items.all()
    print(all_user_items)
    tot_cost = 0
    for i in all_user_items:
        print(i.quantity)
        tot_cost += i.itemtotal
    print(tot_cost)
    num_items_in_cart=user.profile.cart_items.all().count()
    return render(request, 'cart/shopping-cart.html', {'num_items_in_cart': num_items_in_cart, 'all_user_items': all_user_items, 'tot_cost': tot_cost})



@csrf_exempt
def searchnearbyshops(request):
    print("HELO RE")
     
    print(request.method)
    all_shops = (Shop.objects.order_by('distance'))
    shops = all_shops
    num_shops = all_shops.count()
    ans=[]
    for shop in all_shops:
        dic={}
        dic['name'] = shop.shop_name
        dic['lat'] = shop.latitude
        dic['lng'] = shop.longitude
        ans.append(dic)
    list = ans
    json_list = json.dumps(list)
    lat1=0.0
    lon1=0.0
    if 1==1:
        lat1 = 11.5450
        lon1 = 79.5212
        # print(request.POST['lat'],request.POST['lon'])
        lati = float(lat1)
        loni = float(lon1)
        print(lati, loni)

        for shop in Shop.objects.all():
            lat2 = shop.latitude
            lon2 = shop.longitude
            lon1, lat1, lon2, lat2 = map(radians, [loni, lati, lon2, lat2])
            # haversine formula 
            dlon = lon2 - lon1 
            dlat = lat2 - lat1 
            a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
            c = 2 * asin(sqrt(a)) 
            r = 6371 # Radius of earth in kilometers. Use 3956 for miles
            ans = c*r
            print(ans)
            shop.distance = ans
            shop.save()

        all_shops =  (Shop.objects.order_by('distance'))
        ans=[]
        for shop in all_shops:
            dic={}
            dic['name'] = shop.shop_name
            dic['lat'] = shop.latitude
            dic['lng'] = shop.longitude
            ans.append(dic)
        print("SHops are: ")
        print(all_shops)

        # json_list = simplejson.dumps(list)
        
        list = ans
        json_list = json.dumps(list)
        # render_to_response(template_name, {'json_list': json_list})
        print(lati, loni)
        return render(request, 'cart/shop_locator.html', {'all_shops': json_list, 'shops': shops, 'num_shops': num_shops, 'lati': lati, 'loni': loni, 'shop_active': 'active'})
    # return redirect("user:profile")
    return render(request, 'cart/shop_locator.html', {'all_shops': json_list, 'shops': shops, 'num_shops': num_shops, 'lati': lat1, 'loni': lon1, 'shop_active':'active'})

def maps(request):
    return render(request, 'cart/map.html')

def search(request):
    print(request.method)
    if request.method == 'POST':
        itemname = request.POST.get('inp')
        print(itemname)
        item_obj = Item.objects.filter(name=itemname)
        num_items_in_cart = item_obj.count()
        if num_items_in_cart==0:
            messages.warning(request, "No such item!!")
            return redirect('cart:searchpage')
        context = {'all_items': item_obj , 'num_items_in_cart': num_items_in_cart}
        return render(request, 'cart/product_card.html', context)


def searchpage(request):
    all_items = Item.objects.all()
    user = request.user
    paginator = Paginator(all_items, 6)
    page = request.GET.get('page')
    all_items = paginator.get_page(page)
    # paginate_by = 2
    if not user.is_authenticated:
        num_items_in_cart=0
    else:
        num_items_in_cart = user.profile.cart_items.all().count()
    context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'order_active': 'active'}
    return render(request, 'cart/product_card.html', context)

def sort_alphabet(request):
    lis = Item.objects.order_by('name')
    print(lis)
    user = request.user
    paginator = Paginator(lis, 3)
    page = request.GET.get('page')
    lis = paginator.get_page(page)
    # paginate_by = 2
    if not user.is_authenticated:
        num_items_in_cart=0
    else:
        num_items_in_cart = user.profile.cart_items.all().count()
    context = {'all_items': lis , 'num_items_in_cart': num_items_in_cart, 'order_active': 'active', }
    return render(request, 'cart/product_card.html', context)

def sort_price(request):
    lis = Item.objects.order_by('price')
    print(lis)
    user = request.user
    paginator = Paginator(lis, 3)
    page = request.GET.get('page')
    lis = paginator.get_page(page)
    # paginate_by = 2
    if not user.is_authenticated:
        num_items_in_cart=0
    else:
        num_items_in_cart = user.profile.cart_items.all().count()

home/views.py
from django.shortcuts import render
from cart.models import Item, Cart

# Create your views here.
def landing(request):
    all_items = Item.objects.all()
    if not request.user.is_authenticated:
        print('No one inside the app')
        num_items_in_cart = 0
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage1.html', context)
    else:
        user = request.user
        num_items_in_cart = user.profile.cart_items.all().count()
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage1.html', context)


def about(request):
    return render(request, 'home/about.html', {'about_active':'active'})

def contact(request):
    return render(request, 'home/contact.html', {'contact_active':'active'})

cart/templates/cart/chat.html
<html>
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  intent="WELCOME"
  chat-title="Chatwithus..."
  agent-id="8de8323e-3585-435f-8bfc-e12f9f1b1a33"
  language-code="en"
></df-messenger>
</html>

cart/templates/cart/product_card.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Online Medicine Ordering</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link href="{% static 'assets/fonts/icomoon/style.css' %}">
  
    <link href="{% static 'assets/css/bootstrap.min.css' %}">
    <link href="{% static 'assets/css/magnific-popup.css' %}">
    <link href="{% static 'assets/css/jquery-ui.css' %}">
    <link href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link href="{% static 'assets/css/owl.theme.default.min.css' %}">
  
  
    <link href="{% static 'assets/css/aos.css' %}">
  
    <link href="{% static 'home/style1.css' %}">
    <script type="text/javascript" src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  
  </head>


<body>

  <div class="site-wrap">
    {% include 'home/header.html' %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Store</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        
        <div class="row sea">
          <div class="col-lg-6">
              <form action="{% url 'cart:search' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="inp" id="id_inp" class="form-control" placeholder="Search keyword and hit enter...">
              </form>
          </div>
          <div class="col-lg-3">
            <button type="button" class="btn btn-secondary btn-md dropdown-toggle px-4" id="dropdownMenuReference"
              data-toggle="dropdown">Filter By</button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
              <a class="dropdown-item" href="{% url 'cart:sort_alphabet' %}">Name, A to Z</a>
              <a class="dropdown-item" href="{% url 'cart:sort_desc_alphabet' %}">Name, Z to A</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'cart:sort_price' %}">Price, low to high</a>
              <a class="dropdown-item" href="{% url 'cart:sort_desc_price' %}">Price, high to low</a>
            </div>
          </div>

          
          <div class="col-lg-3">
            <a type="button" href="{% url 'cart:ocr' %}" class="btn btn-secondary btn-md">Prescription &nbsp;&nbsp;<i class="fa fa-upload"></i></a>
          </div>
        </div>
        <br>
    
        <div class="row">
          {% for item in all_items %}
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="{% url 'cart:product_page' item.id %}"> <img src="{{item.image}}" alt="Image" height="200px" width="200px"></a>
            <h3 class="text-dark"><a href="{% url 'cart:product_page' item.id %}">{{item.name}}</a></h3>
            <p class="price">Rs. {{item.price}}</p>
            <button type="button" class="btn btn-secondary btn-md"><a style="color:white;" href="{% url 'cart:add_to_cart' item.id %}">Add to Cart</a></button>
          </div>
          {%endfor%}
        </div>
    {% if all_items.paginator.num_pages > 1 %}
        {% include 'cart/pagination.html' with items=all_items %}
    {% endif %}

    <br><br>


    
    <!-- <div class="site-section bg-secondary bg-image">
      <div class="container">
        <div class="row align-items-stretch">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="part1 banner-1 h-100 d-flex" >
              <div class="banner-1-inner align-self-center">
                <h2>Pharma Products</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                </p>
              </div>
            </a>
          </div>
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="part2 banner-1 h-100 d-flex">
              <div class="banner-1-inner ml-auto  align-self-center">
                <h2>Rated by Experts</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div> -->

    {% include 'home/footer.html' %}

  </div>

    <script type="text/javascript" src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/aos.js' %}"></script>

    <script type="text/javascript" src="{% static 'assets/js/main.js' %}"></script>

    <script>
      AOS.init({
      duration: 800,
      easing: 'slide',
      once: true
    });
   
   jQuery(document).ready(function($) {
   
     "use strict";
   
     var slider = function() {
       $('.nonloop-block-3').owlCarousel({
         center: false,
         items: 1,
         loop: true,
         smartSpeed: 700,
         stagePadding: 15,
         margin: 20,
         autoplay: true,
         nav: true,
         navText: ['<span class="icon-arrow_back">', '<span class="icon-arrow_forward">'],
         responsive:{
           600:{
             margin: 20,
             items: 2
           },
           1000:{
             margin: 20,
             items: 3
           },
           1200:{
             margin: 20,
             items: 3
           }
         }
       });
     };
     slider();
   
   
     var siteMenuClone = function() {
   
       $('<div class="site-mobile-menu"></div>').prependTo('.site-wrap');
   
       $('<div class="site-mobile-menu-header"></div>').prependTo('.site-mobile-menu');
       $('<div class="site-mobile-menu-close "></div>').prependTo('.site-mobile-menu-header');
       $('<div class="site-mobile-menu-logo"></div>').prependTo('.site-mobile-menu-header');
   
       $('<div class="site-mobile-menu-body"></div>').appendTo('.site-mobile-menu');
   
       
   
       $('.js-logo-clone').clone().appendTo('.site-mobile-menu-logo');
   
       $('<span class="ion-ios-close js-menu-toggle"></div>').prependTo('.site-mobile-menu-close');
       
   
       $('.js-clone-nav').each(function() {
         var $this = $(this);
         $this.clone().attr('class', 'site-nav-wrap').appendTo('.site-mobile-menu-body');
       });
   
   
       setTimeout(function() {
         
         var counter = 0;
         $('.site-mobile-menu .has-children').each(function(){
           var $this = $(this);
           
           $this.prepend('<span class="arrow-collapse collapsed">');
   
           $this.find('.arrow-collapse').attr({
             'data-toggle' : 'collapse',
             'data-target' : '#collapseItem' + counter,
           });
   
           $this.find('> ul').attr({
             'class' : 'collapse',
             'id' : 'collapseItem' + counter,
           });
   
           counter++;
   
         });
   
       }, 1000);
   
       $('body').on('click', '.arrow-collapse', function(e) {
         var $this = $(this);
         if ( $this.closest('li').find('.collapse').hasClass('show') ) {
           $this.removeClass('active');
         } else {
           $this.addClass('active');
         }
         e.preventDefault();  
         
       });
   
       $(window).resize(function() {
         var $this = $(this),
           w = $this.width();
   
         if ( w > 768 ) {
           if ( $('body').hasClass('offcanvas-menu') ) {
             $('body').removeClass('offcanvas-menu');
           }
         }
       })
   
       $('body').on('click', '.js-menu-toggle', function(e) {
         var $this = $(this);
         e.preventDefault();
   
         if ( $('body').hasClass('offcanvas-menu') ) {
           $('body').removeClass('offcanvas-menu');
           $this.removeClass('active');
         } else {
           $('body').addClass('offcanvas-menu');
           $this.addClass('active');
         }
       }) 
   
       // click outisde offcanvas
       $(document).mouseup(function(e) {
         var container = $(".site-mobile-menu");
         if (!container.is(e.target) && container.has(e.target).length === 0) {
           if ( $('body').hasClass('offcanvas-menu') ) {
             $('body').removeClass('offcanvas-menu');
           }
         }
       });
     }; 
     siteMenuClone();
   
   
     var sitePlusMinus = function() {
       $('.js-btn-minus').on('click', function(e){
         e.preventDefault();
         if ( $(this).closest('.input-group').find('.form-control').val() != 0  ) {
           $(this).closest('.input-group').find('.form-control').val(parseInt($(this).closest('.input-group').find('.form-control').val()) - 1);
         } else {
           $(this).closest('.input-group').find('.form-control').val(parseInt(0));
         }
       });
       $('.js-btn-plus').on('click', function(e){
         e.preventDefault();
         $(this).closest('.input-group').find('.form-control').val(parseInt($(this).closest('.input-group').find('.form-control').val()) + 1);
       });
     };
     sitePlusMinus();
   
   
     var siteSliderRange = function() {
       $( "#slider-range" ).slider({
         range: true,
         min: 0,
         max: 500,
         values: [ 75, 300 ],
         slide: function( event, ui ) {
           $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
         }
       });
       $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
         " - $" + $( "#slider-range" ).slider( "values", 1 ) );
     };
     siteSliderRange();
   
   
     var siteMagnificPopup = function() {
       $('.image-popup').magnificPopup({
         type: 'image',
         closeOnContentClick: true,
         closeBtnInside: false,
         fixedContentPos: true,
         mainClass: 'mfp-no-margins mfp-with-zoom', // class to remove default margin from left and right side
          gallery: {
           enabled: true,
           navigateByImgClick: true,
           preload: [0,1] // Will preload 0 - before current, and 1 after the current image
         },
         image: {
           verticalFit: true
         },
         zoom: {
           enabled: true,
           duration: 300 // don't foget to change the duration also in CSS
         }
       });
   
       $('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({
         disableOn: 700,
         type: 'iframe',
         mainClass: 'mfp-fade',
         removalDelay: 160,
         preloader: false,
   
         fixedContentPos: false
       });
     };
     siteMagnificPopup();
   
     var searchShow = function() {
       // alert();
       var searchWrap = $('.search-wrap');
       $('.js-search-open').on('click', function(e) {
         e.preventDefault();
         searchWrap.addClass('active');
         setTimeout(function() {
           searchWrap.find('.form-control').focus();
         }, 300);
       });
       $('.js-search-close').on('click', function(e) {
         e.preventDefault();
         searchWrap.removeClass('active');
       })
     };
     searchShow();
   
   });
   </script>

</body>



</html>