cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    # url(r'^home1', views.home1, name='home1'),
    # url(r'^uploads/simple/', views.simple_upload, name='simple_upload'),
    # url(r'^uploads/form/', views.model_form_upload, name='model_form_upload'),
    url(r'^ocr/$', views.ocr, name='ocr'),
    url(r'^maps', views.maps, name='maps'),
    url(r'^home/', views.home, name='home'),
    url(r'^add_item/', views.add_item, name='add_item'),
    url(r'^itemlist/', views.itemlist, name='itemlist'),
    url(r'^shoppingcart/', views.shoppingcart, name='shoppingcart'),
    url(r'^search/', views.searchpage , name='searchpage'),
    url(r'^searchnearbyshops/', views.searchnearbyshops , name='searchnearbyshops'),
    url(r'^searchitem/', views.search , name='search'),
    url(r'^sort_alphabet/', views.sort_alphabet , name='sort_alphabet'),
    url(r'^sort_desc_alphabet/', views.sort_desc_alphabet , name='sort_desc_alphabet'),
    url(r'^sort_price/', views.sort_price , name='sort_price'),
    url(r'^sort_desc_price/', views.sort_desc_price , name='sort_desc_price'),
    # url(r'^ocr/', ocr_view, name='ocr_view'),
    # url(r'^ocrform/', ocr_form_view, name='ocr_form_view'),
    url(r'^checkout/', views.checkout , name='checkout'),
    url(r'^productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url(r'^add_to_cart/(?P<Item_id>[0-9]+)',views.add_to_cart, name='add_to_cart'),
    url(r'^remove_from_cart/(?P<Item_id>[0-9]+)',views.remove_from_cart, name='remove_from_cart'),
    url(r'^remove_single_item_from_cart/(?P<Item_id>[0-9]+)',views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url(r'^add_single_item_into_cart/(?P<Item_id>[0-9]+)',views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

home/urls.py
from django.urls import path, include 
from django.conf import settings 
from . import views
from user import views as user_view 
from django.contrib.auth import views as auth
from django.conf.urls.static import static 
from django.conf.urls import url
from django.contrib.auth import views as auth_views


app_name = 'home'

urlpatterns=[
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

user/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from user import views as user_view
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    # path('', views.index, name ='index'),
    # path('login/', user_view.Login, name='login'),
    path('loginuser/', user_view.loginuser, name='loginuser'),
    path('loginshop/', user_view.LoginShop, name='loginshop'),
    path('profile/', user_view.profilepage, name='profile'),
    path('logout/', auth.LogoutView.as_view(template_name='home/landingpage1.html'), name='logout'),
    path('mainregister/', user_view.mainRegister, name='mainRegister'),
    path('mainlogin/', user_view.mainLogin, name='mainLogin'),
    path('register/', user_view.register, name='register'),
    path('registerShop/', user_view.registerShop, name='registerShop'),
    path('user/sent/', user_view.activation_sent_view, name="activation_sent"),
    path('user/activate/<slug:uidb64>/<slug:token>/', user_view.activate, name='activate'),
    # url('^', include('django.contrib.auth.urls')),
    # path('accounts/', include('allauth.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name ='user/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from cart.models import Item, Cart

# Create your views here.
def landing(request):
    all_items = Item.objects.all()
    if not request.user.is_authenticated:
        print('No one inside the app')
        num_items_in_cart = 0
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage1.html', context)
    else:
        user = request.user
        num_items_in_cart = user.profile.cart_items.all().count()
        context = {'all_items': all_items , 'num_items_in_cart': num_items_in_cart, 'home_active':'active'}
        return render(request, 'home/landingpage1.html', context)


def about(request):
    return render(request, 'home/about.html', {'about_active':'active'})

def contact(request):
    return render(request, 'home/contact.html', {'contact_active':'active'})

home/templates/home/footer.html
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

        <div class="block-7">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>We deliver medicines at your doorstep. No more going to pharmacies. We provide safe and quick delivery from your nearest stores.</p>
        </div>

      </div>
      <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
        <h3 class="footer-heading mb-4">Quick Links</h3>
        <ul class="list-unstyled">
          <li><a href="{% url 'cart:searchpage' %}">Supplements</a></li>
          <li><a href="{% url 'cart:searchpage' %}">Vitamins</a></li>
          <li><a href="{% url 'cart:searchpage' %}">Diet &amp; Nutrition</a></li>
          <li><a href="{% url 'cart:searchpage' %}">Tea &amp; Coffee</a></li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-3">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>

          <div class="row">
            <div class="col-md-2 col-lg-2"><i class="fa fa-map-marker"></i></div>
            <div class="col-md-10 col-lg-10">Fake St. Street, Andhra Pradesh, India></div>
          </div>

          <div class="row">
            <div class="col-md-2 col-lg-2"><i class="fa fa-phone"></i></div>
            <div class="col-md-10 col-lg-10"><a href="tel://23923929210">+2 392 3929 210</a></div>
          </div>

          <div class="row">
            <div class="col-md-2 col-lg-2"><i class="fa fa-envelope"></i></div>
            <div class="col-md-10 col-lg-10">emailaddress@domain.com</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

home/templates/home/landingpage1.html
{% load static %}
<link href="{% static 'home/style1.css' %}" rel=text/stylesheet>

<body>

  <div class="site-wrap">

    {% include 'home/header.html' %}

    <div class="site-blocks-cover">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
            <div class="site-block-cover-content text-center">
              <h2 class="sub-title">Effective Help, New Services</h2>
              <h1>Welcome To Eco-Buddy</h1>
              <p>
                <a href="{% url 'cart:searchpage' %}" class="btn btn-primary px-5 py-3">Shop Now</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row align-items-stretch section-overlap">
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="banner-wrap bg-primary h-100">
              <a href="#" class="h-100">
                <h5>Free <br> Shipping</h5>
                <p>
                  No delivery charges
                  <strong>Get your medicines at your door, without any extra charge!</strong>
                </p>
              </a>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="banner-wrap h-100">
              <a href="#" class="h-100">
                <h5>Season <br> Sale 50% Off</h5>
                <p>
                  Don't miss it
                  <strong>Hurry now! The sale is about to end.</strong>
                </p>
              </a>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="banner-wrap bg-warning h-100">
              <a href="#" class="h-100">
                <h5>Buy <br> A Gift Card</h5>
                <p>
                  To your family or friends
                  <strong>Gift someone with chronic illness a coupon and help them stay healthy!</strong>
                </p>
              </a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">Popular Products</h2>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <span class="tag">Sale</span>
            <a href="#"> <img src="https://www.netmeds.com/images/category/3065/thumb/Mask_gloves_and%20_Protective%20_equipment_0.jpg" alt="Image"></a>
            <h3 class="text-dark"><a href="#">Masks, Gloves and protective equipment</a></h3>
            <p class="price">Upto 30% off</p>
          </div>
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="#"> <img src="https://www.lubisolar.com/wp-content/uploads/2018/09/house-for-sales-solar-panel-installation-2.jpg" width="200px" height="200px" alt="Image"></a>
            <h3 class="text-dark"><a href="#">Solar Panel Installation</a></h3>
            <p class="price">Rs. 27.00</p>
          </div>
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="#"> <img src="https://naturalmedicinenh.com/wp-content/uploads/2015/09/spa.jpg" width="200px" height="180px" alt="Image" style="padding-top: 40px;"></a>
            <h3 class="text-dark"><a href="#">Organic Spa</a></h3>
            <p class="price">Rs. 130.00</p>
          </div>

          <!-- <div class="col-sm-6 col-lg-4 text-center item mb-4">

            <a href="shop-single.html"> <img src="https://i.pinimg.com/originals/c2/2c/58/c22c584dae72f372bf0b94adfe9c6634.jpg" width="200px" height="200px" alt="Image"></a>
            <h3 class="text-dark"><a href="shop-single.html">Move Free</a></h3>
            <p class="price"><del>Rs. 6000</del> &mdash; Rs. 4995</p>
          </div>
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <a href="shop-single.html"> <img src="https://images-na.ssl-images-amazon.com/images/I/71zb3d5VXdL._SX466_.jpg" width="200px" height="200px" alt="Image"></a>
            <h3 class="text-dark"><a href="shop-single.html">Vicks</a></h3>
            <p class="price">Rs. 20.00</p>
          </div>
          <div class="col-sm-6 col-lg-4 text-center item mb-4">
            <span class="tag">Sale</span>
            <a href="shop-single.html"> <img src="https://res.cloudinary.com/du8msdgbj/images/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1589828157/ntryzimuazmbxxupvobw/combiflam-icy-hot-fast-pain-relief-spray.jpg" width="200px" height="200px" alt="Image"></a>
            <h3 class="text-dark"><a href="shop-single.html">Combiflam</a></h3>
            <p class="price"><del>Rs. 150</del> &mdash; Rs. 117</p>
          </div>
        </div> -->
        <div class="row mt-5">
          <div class="col-12 text-center">
            <a href="{% url 'cart:itemlist' %}" class="btn btn-primary px-4 py-3">View All Products</a>
          </div>
        </div>
      </div>
    </div>

    
    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">New Products</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 block-3 products-wrap">
            <div class="nonloop-block-3 owl-carousel">

              <!-- <div class="text-center item mb-4">
                <a href="shop-single.html"> <img src="{ % static 'assets/images/product_05.png' %}" alt="Image3"></a>
                <h3 class="text-dark"><a href="shop-single.html">Umcka Cold Care</a></h3>
                <p class="price">$120.00</p>
              </div> -->

              <!-- <div class="text-center item mb-4">
                <a href="shop-single.html"> <img src="{% static 'assets/images/product_01.png' %}" alt="Image"></a>
                <h3 class="text-dark"><a href="shop-single.html">Bioderma</a></h3>
                <p class="price">Rs. 620.00</p>
              </div>

              <div class="text-center item mb-4">
                <a href="shop-single.html"> <img src="{% static 'assets/images/product_02.png' %}" alt="Image"></a>
                <h3 class="text-dark"><a href="shop-single.html">Chanca Piedra</a></h3>
                <p class="price">Rs. 1200.00</p>
              </div>

              <div class="text-center item mb-4">
                <a href="shop-single.html"> <img src="{% static 'assets/images/product_04.png' %}" alt="Image"></a>
                <h3 class="text-dark"><a href="shop-single.html">Cetyl Pure</a></h3>
                <p class="price">Rs. 560.00</p>
              </div> -->

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">Testimonials</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 block-3 products-wrap">
            <div class="nonloop-block-3 no-direction owl-carousel">
        
              <div class="testimony">
                <blockquote>
                  <img src="{% static 'assets/images/person_1.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                  <p>&ldquo;Really amazing app, works smoothly and great service. Over and above all of that a 18%* discount! That's a complete wow factor right there. Almost my entire family uses this one. Highly recommend to all.&rdquo;</p>
                </blockquote>

                <p>&mdash; Kelly Holmes</p>
              </div>
        
              <div class="testimony">
                <blockquote>
                  <img src="{% static 'assets/images/person_2.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                  <p>&ldquo;It's a super cool app with super discounts. Purchasing medicine has become so easy. It takes care of all my family medical needs. Very simple, smooth and useful.&rdquo;</p>
                </blockquote>
              
                <p>&mdash; Rebecca Morando</p>
              </div>
        
              <div class="testimony">
                <blockquote>
                  <img src="{% static 'assets/images/person_3.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                  <p>&ldquo;Pharma has saved lots of time and money by delivering medicines at my home and also giving 18%* discount. I always order medicines in the morning and by evening they get delivered. Too good and easy to use.&rdquo;</p>
                </blockquote>
              
                <p>&mdash; Lucas Gallone</p>
              </div>
        
              <div class="testimony">
                <blockquote>
                  <img src="{% static 'assets/images/person_4.jpg' %}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                  <p>&ldquo;Really amazing app, works smoothly and great service. Over and above all of that a 18%* discount! That's a complete wow factor right there. Almost my entire family uses this one. Highly recommend to all.&rdquo;</p>
                </blockquote>
              
                <p>&mdash; Andrew Neel</p>
              </div>
        
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- <div class="site-section bg-secondary bg-image">
      <div class="container">
        <div class="row align-items-stretch">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="part1 banner-1 h-100 d-flex">
              <div class="banner-1-inner align-self-center">
                <h2>Pharma Products</h2>
                <p>We deliver authentic products which are safe and help you become healthy again
                </p>
              </div>
            </a>
          </div>
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="part2 banner-1 h-100 d-flex">
              <div class="banner-1-inner ml-auto  align-self-center">
                <h2>Rated by Experts</h2>
                <p>Our app has been tried and tested by experts in various fields. They recommend our app too
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div> -->

    {% include 'home/footer.html' %}
  </div>

  

</body>
<script type="text/javascript" src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/aos.js' %}"></script>

    <script type="text/javascript" src="{% static 'assets/js/main.js' %}"></script>
    

</html>

home/templates/home/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Landing Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet"> -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Forte"> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="{% static 'home/navbar1.css' %}"  rel="stylesheet">
</head>
<body>
  {% block content %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}

 <!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top" id="custom-nav">
    <div class="container-fluid ">
        <a class="navbar-brand waves-effect" href="{% url 'home:landing' %}"><img src="https://image.flaticon.com/icons/png/512/32/32140.png" alt="logo" height="70px"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item {{home_active}}">
                    <a class="nav-link" href="{% url 'home:landing' %}">Home</a>
                </li>
                <li class="nav-item {{order_active}}">
                    <a class="nav-link" href="{% url 'cart:searchpage' %}">Order Medicines</a>
                </li>
                <li class="nav-item {{doctor_active}}">
                    <a class="nav-link" href="#">Search Doctors</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                    {%comment%}
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <span class="p1 fa-stack fa-2x has-badge" data-count="{{ num_items_in_cart }}">
                      <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                    <i class="p3 fas fa-shopping-cart xfa-inverse"></i>
                    </span>
                    {% else %}
                    <span class="p1 fa-stack fa-2x has-badge" data-count="0">
                        <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                      <i class="p3 fas fa-shopping-cart xfa-inverse"></i>
                    {% endif %}
                    <a id="special0" class="nav-link" href="{% url 'cart:shoppingcart' %}">Cart</a>
                </li>
                </div>
                {% if request.user.is_authenticated %}
                
                <li class="nav-item">
                    <a id="special1" class="nav-link" href="{% url 'user:logout' %}">
                        <i class="fas fa-user icon"></i>
                        Logout
                    </a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a id="special2" class="nav-link" href="{% url 'user:mainRegister' %}">
                        <i class="fas fa-user icon"></i>
                        Login
                    </a>
                </li>
                {% endif %}{%endcomment%}

                {% if request.user.is_authenticated %}
                <!-- <div class="cart"> -->
                <li class="nav-item" id='c1'>
                <a href="{% url 'cart:shoppingcart' %}"><span class="p1 fa-stack fa-2x has-badge" data-count="{{ num_items_in_cart }}">
                    <!-- <i class="p2 fa fa-circle fa-stack-2x"></i>  -->
                  <!-- <i class="p3 fas fa-shopping-cart fa-sm xfa-inverse"></i> -->
                  <img src="https://cdn0.iconfinder.com/data/icons/webshop-essentials/100/shopping-cart-512.png" height='40px' width='40px'>
                  </span></a>
                  
                </li>
                <!-- </div> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      <!-- <i class="fas fa-user fa-sm icon"></i> -->
                      <img src="https://icons-for-free.com/iconfiles/png/512/friend+human+man+member+person+profile+user+users+icon-1320168707291252637.png" height='40px' width='40px'>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-default"
                      aria-labelledby="navbarDropdownMenuLink-333" style="top:45px;right:-14px;">
                      <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                      <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>                    </div>
                  </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:mainRegister' %}">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register'%}">
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Navbar
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown
          </a>
          <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default"
            aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav> -->
  <!--/.Navbar -->

  {%endblock%}
</body>

</html>