cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    # url(r'^home1', views.home1, name='home1'),
    # url(r'^uploads/simple/', views.simple_upload, name='simple_upload'),
    # url(r'^uploads/form/', views.model_form_upload, name='model_form_upload'),
    url(r'^ocr/$', views.ocr, name='ocr'),
    url(r'^maps', views.maps, name='maps'),
    url(r'^home/', views.home, name='home'),
    url(r'^add_item/', views.add_item, name='add_item'),
    url(r'^itemlist/', views.itemlist, name='itemlist'),
    url(r'^shoppingcart/', views.shoppingcart, name='shoppingcart'),
    url(r'^search/', views.searchpage , name='searchpage'),
    url(r'^searchnearbyshops/', views.searchnearbyshops , name='searchnearbyshops'),
    url(r'^searchitem/', views.search , name='search'),
    url(r'^sort_alphabet/', views.sort_alphabet , name='sort_alphabet'),
    url(r'^sort_desc_alphabet/', views.sort_desc_alphabet , name='sort_desc_alphabet'),
    url(r'^sort_price/', views.sort_price , name='sort_price'),
    url(r'^sort_desc_price/', views.sort_desc_price , name='sort_desc_price'),
    # url(r'^ocr/', ocr_view, name='ocr_view'),
    # url(r'^ocrform/', ocr_form_view, name='ocr_form_view'),
    url(r'^checkout/', views.checkout , name='checkout'),
    url(r'^productpage/(?P<Id>[0-9]+)', views.product_page, name='product_page'),
    url(r'^add_to_cart/(?P<Item_id>[0-9]+)',views.add_to_cart, name='add_to_cart'),
    url(r'^remove_from_cart/(?P<Item_id>[0-9]+)',views.remove_from_cart, name='remove_from_cart'),
    url(r'^remove_single_item_from_cart/(?P<Item_id>[0-9]+)',views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    url(r'^add_single_item_into_cart/(?P<Item_id>[0-9]+)',views.add_single_item_into_cart, name='add_single_item_into_cart')

]

doctorapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views as user_view
from django.contrib.auth import views as auth_views

# app_name = 'doctorapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='user/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    ##### user related path#########################
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls')),
    path('', include('home.urls')),
    # path('', include('django.contrib.auth.urls'))

]

user/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from user import views as user_view
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    # path('', views.index, name ='index'),
    # path('login/', user_view.Login, name='login'),
    path('loginuser/', user_view.loginuser, name='loginuser'),
    path('loginshop/', user_view.LoginShop, name='loginshop'),
    path('profile/', user_view.profilepage, name='profile'),
    path('logout/', auth.LogoutView.as_view(template_name='home/landingpage1.html'), name='logout'),
    path('mainregister/', user_view.mainRegister, name='mainRegister'),
    path('mainlogin/', user_view.mainLogin, name='mainLogin'),
    path('register/', user_view.register, name='register'),
    path('registerShop/', user_view.registerShop, name='registerShop'),
    path('user/sent/', user_view.activation_sent_view, name="activation_sent"),
    path('user/activate/<slug:uidb64>/<slug:token>/', user_view.activate, name='activate'),
    # url('^', include('django.contrib.auth.urls')),
    # path('accounts/', include('allauth.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name ='user/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'), name='password_reset_confirm')
]

user/models.py
from django.contrib.auth.models import User, AbstractBaseUser
from django.db import models
from cart.models import Cart
from django.db.models.signals import post_save
from django.dispatch import receiver

USER_TYPE = (
    (1, 'users'),
    (2, 'shops')
)

class History(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    ordered_date = models.DateTimeField()
    ordered_items = models.ManyToManyField("cart.Cart")

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE, default=1)
    cart_items=models.ManyToManyField(Cart)
    signup_confirmation = models.BooleanField(default=False)
    address = models.CharField(max_length=256, default=True)
    history = models.ManyToManyField(History)

class Shop(models.Model):
    username = models.CharField(max_length=50, default=True)
    set_password = models.CharField(max_length=50, default=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE, default=2)
    shop_name = models.CharField(max_length=256, default=True)
    shop_registration_no = models.CharField(max_length=256, default=True)
    address = models.CharField(max_length=256, default=True)
    latitude = models.FloatField(max_length=50, default=0)
    longitude = models.FloatField(max_length=50, default=0)
    distance = models.FloatField(max_length=50, default=0)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.shop_name

@receiver(post_save,sender=User)
def update_profile_signal(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

user/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm 
from .models import Shop

class UserRegisterForm(UserCreationForm): 
	email = forms.EmailField() 
	phone_no = forms.CharField(max_length = 20) 
	# first_name = forms.CharField(max_length = 20) 
	# last_name = forms.CharField(max_length = 20) 
	class Meta: 
		model = User 
		fields = ['username', 'email', 'phone_no', 'password1', 'password2'] 

class ShopRegisterForm(UserCreationForm):
	username = forms.CharField(max_length=50)
	password1 = forms.CharField(max_length=20)
	password2 = forms.CharField(max_length=20)
	email = forms.EmailField()
	address = forms.CharField(max_length=250)
	phone_no = forms.CharField(max_length = 20)
	shop_name = forms.CharField(max_length = 50)
	shop_registration_no = forms.CharField(max_length = 30)

	class Meta:
		model = Shop
		fields = ['username', 'email', 'phone_no','address','password1', 'password2', 'shop_name', 'shop_registration_no']

user/views.py
# Create your views here.
import requests
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.forms import AuthenticationForm 
from .forms import UserRegisterForm, ShopRegisterForm
from django.core.mail import send_mail,EmailMultiAlternatives 
from django.template.loader import get_template 
from django.template import Context 
from django.contrib.auth.models import User
from .models import Shop
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.db import IntegrityError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMessage
import urllib.parse
from cart.models import Item

def mainRegister(request):
	return render(request, 'user/main_signup.html', {'users' : 1, 'shops': 2})

def mainLogin(request):
	return render(request, 'user/main_login.html')

def index(request):
	user = request.user
	num_items_in_cart=user.profile.cart_items.all().count()
	return render(request, 'home/navbar.html',{'num_items_in_cart':num_items_in_cart})


def activation_sent_view(request):
    return render(request, 'user/activation_sent.html')

def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	print(account_activation_token.check_token(user, token))
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.profile.signup_confirmation = True
		user.save()
		login(request, user, backend='django.contrib.auth.backends.ModelBackend')
		return redirect('home:landing')
	else:
		return render(request, 'user/activation_invalid.html')


def register(request): 
	if request.method == 'POST':	
		form = UserRegisterForm(request.POST)
		print(form)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()
			user.profile.email = form.cleaned_data.get('email')
			user.is_active = False
			user.user_type = 1
			user.save()
			current_site = get_current_site(request)
			print(current_site)
			subject = 'Please activate your Account'
			message = render_to_string('user/activation_request.html', {
				'user': user,
				'domain': '127.0.0.1:8000',
				'uid': urlsafe_base64_encode(force_bytes(user.pk)),
				'token': account_activation_token.make_token(user),
			})
			print(message)
			email = EmailMessage('email_subject', message, to=[user.profile.email])
			email.send()
			messages.success(request, "Your account has been created ! You are now able to log in")
			return redirect('user:activation_sent')
	else: 
		form = UserRegisterForm()
	return render(request, 'user/user_register.html', {'form': form, 'title':'reqister here'}) 


def registerShop(request):
	if request.method == 'POST':
		print("HIIIIIIIIIIIIIIIIIIIIIIIIIIIii")	
		form = ShopRegisterForm(request.POST or None)
		print(form)
		if form.is_valid():
			user = form.save
			shop = Shop()
			print(user)
			# user.refresh_from_db()
			shop.username = form.cleaned_data['username']
			shop.set_password = form.cleaned_data['password1']
			shop.email = form.cleaned_data['email']
			shop.address = form.cleaned_data['address']
			shop.shop_name = form.cleaned_data['shop_name']
			shop.shop_registration_no = form.cleaned_data['shop_registration_no']
			shop.save()
			us = User.objects.create_user(username=shop.username,email=shop.email,password=shop.set_password)
			us.save()
			print(shop.address)

			# is_active = False
			shop.user_type = 2

			url = 'https://nominatim.openstreetmap.org/search/' + urllib.parse.quote(shop.address) +'?format=json'
			response = requests.get(url).json()
			print(response[0]["lat"])
			print(response[0]["lon"])
			lat = response[0]["lat"]
			lon = response[0]["lon"]
			print(lat, lon)
			shop.latitude = lat
			shop.longitude = lon
			shop.save()
			
			current_site = get_current_site(request)
			subject = 'Please activate your Account'
			# message = render_to_string('user/activation_request.html', {
			# 	'user': user,
			# 	'domain': current_site.domain,
			# 	'uid': urlsafe_base64_encode(force_bytes(user.pk)),
			# 	'token': account_activation_token.make_token(user),
			# })
			# print(message)
			message = "Hello"
			email = EmailMessage('email_subject', message, to=[shop.email])
			email.send()
			messages.success(request, "Your account has been created ! You are now able to log in")
			return redirect('user:activation_sent')
	else: 
		form = ShopRegisterForm()
	return render(request,'user/shop_signup.html')
	# return render(request, 'user/shop_signup.html', {'form': form, 'title':'reqister here'})

def loginuser(request):
	if request.method=="POST":
		username=request.POST.get('username')
		password=request.POST.get('password1')
		print(username)
		print(password)
		user=authenticate(request, username=username, password=password)
		print(user)
		if user is not None:
			form=login(request, user)
			print(form)
			messages.success(request, f'Welcome {username} !!')
			user = request.user
			user.save()
			# print(user.profile.bio)
			return redirect('home:landing')
		else:
			messages.warning(request, "Such a user does not exist!!")
			# return redirect('user:register')
	form=AuthenticationForm()

	return render(request, 'user/user_login.html', {'form':form, 'title':'log in'})


# def Login(request):
# 	if request.method=="POST":
# 		username=request.POST.get('username')
# 		password=request.POST.get('password1')
# 		print(username)
# 		print(password)
# 		user=authenticate(request, username=username, password=password)
# 		print(user)
# 		if user is not None:
# 			form=login(request, user)
# 			print(form)
# 			messages.success(request, f'Welcome {username} !!')
# 			user = request.user
# 			user.save()
# 			# print(user.profile.bio)
# 			return redirect('home:landing')
# 		else:
# 			messages.warning(request, "Such a user does not exist!!")
# 			# return redirect('user:register')
# 	form=AuthenticationForm()

# 	return render(request, 'user/user_login.html', {'form':form, 'title':'log in'})


def LoginShop(request):
	if request.method=="POST":
		username = request.POST.get('username')
		registration_no = request.POST.get("shop_registration_no")
		password = request.POST.get('password1')
		user=authenticate(request, username=username, password=password)
		if user is None:
			print("Wrong User")
			messages.warning(request, "Wrong credentials or Invalid User")
		else:
			flag=0
			if Shop.objects.filter(shop_registration_no=registration_no):
				flag = 1
			form = login(request,user, backend='django.contrib.auth.backends.ModelBackend')
			print(form)
			all_items = Item.objects.all()
			return render(request, 'cart/shop_dash.html', {'all_items': all_items})

	return render(request, 'user/shop_login.html')

def profilepage(request):
	user=request.user
	all_items = user.profile.cart_items.all()
	num_items_in_cart = all_items.count()
	# print(all_items)
	context = {'all_items':all_items, 'num_items_in_cart':num_items_in_cart}
	return render(request, 'user/profile.html', context)

user/templates/user/activation_invalid.html
<h3>Activation Invalid!!</h3>

user/templates/user/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

user/templates/user/activation_sent.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<div class="alert alert-success" role="alert" id="success_message">Success!! <i class="glyphicon glyphicon-thumbs-up"></i> PLease activate your account. Activation link has been sent in your email.</div>

user/templates/user/logged_out.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

user/templates/user/main_login.html
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    
   
   <!-- <link href="login_page_1.css" rel="stylesheet"> -->
</head>
{% include 'home/header.html' %}
<br>

  <center><h2>Main Login</h2>
    <p class="lead">Select below the type of account you want to create</p>
    <a href="{% url 'user:loginuser'%}" class="btn btn-lg btn-primary mr-5" role="button">User</a>
    
    <a href="{% url 'user:loginshop'%}" class="btn btn-lg btn-primary" role="button">Shop</a>
  </center>

user/templates/user/main_signup.html
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    
   
   <!-- <link href="login_page_1.css" rel="stylesheet"> -->
</head>
{% include 'home/header.html' %}
<br>
<br>

  <center><h2>Main Signup</h2>
    <p class="lead">Select below the type of account you want to create</p>
    <a href="{% url 'user:register'%}" class="btn btn-lg btn-primary mr-5" role="button">User</a>
    <a href="{% url 'user:registerShop'%}" class="btn btn-lg btn-primary" role="button">Shop</a>
  </center>

user/templates/user/password_reset.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<head>
  <title>Payment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'user/password-reset.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'user/password_reset.css' %}"> -->



</head>
<body>
    <div class="block-heading">
        <h2>Reset Password</h2>
    </div>
    <div class="content-section shadow p-3 mb-5 bg-blue rounded">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-sm-12 col-md-12">
                <label for="email">Email</label>
                <input type="email" class="form-control m-0" placeholder="Email Address" id="email">
                </div>
                <div class="form-group col-sm-12 col-md-12">
                    <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
                </div>
            </div>
        </form>
    </div>
</body>

user/templates/user/password_reset_done.html
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>

user/templates/user/shop_register.html
{% load static %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js"></script>

<div class="container" style="margin-top:2%">

    <form role='form' data-toggle="validator" class="well form-horizontal" action="{% url 'user:registerShop' %}" method="post"  id="contact_form">
<fieldset>
{% csrf_token %}
<!-- Form Name -->
<legend>Join Us Today!</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Username</label>
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="username" id ='id_username' placeholder="username" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Password</label>
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="password1" id ='id_password1' placeholder="Enter your Password" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Confirm Password</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="password2" id="id_password2" data-match="#id_password1" data-match-error="Password doesn't match" placeholder="Confirm your Password" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">E-Mail</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="email" id="id_email" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Shop Name</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="shop_name" id="id_shop_name" placeholder="shop name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Shop Registration Number</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="shop_registration_no" id="id_shop_registration_no" placeholder="shop registration no" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Phone #</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input name="phone" id="id_phone" placeholder="(845)555-1212" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Address</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="address" id="id_address" placeholder="Address" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">City</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="city" id="id_city" placeholder="city" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Select Basic -->

<div class="form-group">
  <label class="col-md-4 control-label">State</label>
    <div class="col-md-4 selectContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
    <select name="state" class="form-control selectpicker" >
      <option value=" " >Please select your state</option>
      <option>Andhra Pradesh</option>
      <option>Andaman and Nicobar Islands</option>
      <option>Arunachal Pradesh</option>
      <option>Assam</option>
      <option>Bihar</option>
      <option>Chandigarh</option>
      <option>Chhattisgarh</option>
      <option>Delhi</option>
      <option>Goa</option>
      <option>Gujarat</option>
      <option>Haryana</option>
      <option>Himachal Pradesh</option>
      <option>Jammu and Kashmir</option>
      <option>Jharkhand</option>
      <option>Karnataka</option>
      <option>Kerala</option>
      <option>Ladakh</option>
      <option>Lakshadweep</option>
      <option>Madhya Pradesh</option>
      <option>Maharashtra</option>
      <option>Manipur</option>
      <option>Meghalaya</option>
      <option>Mizoram</option>
      <option>Nagaland</option>
      <option>Odisha</option>
      <option>Puducherry</option>
      <option>Punjab</option>
      <option>Rajasthan</option>
      <option>Sikkim</option>
      <option>Tamil Nadu</option>
      <option>Telangana</option>
      <option>Tripura</option>
      <option>Uttar Pradesh</option>
      <option>Uttarakhand</option>
      <option>West Bengal</option>

    </select>
  </div>
</div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Zip Code</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="zip" id="id_zip" placeholder="Zip Code" class="form-control"  type="text">
    </div>
</div>
</div>


<!-- Success message -->

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
    <button type="submit" class="btn btn-warning" >SignUp <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->


<script type="text/javascript" src="{% static 'user/shop_register.js' %}" ></script>